# Generated by Django 4.2.5 on 2023-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_first_admin',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_pending_approval',
            field=models.BooleanField(default=None),
        ),
    ]
