# Generated by Django 4.2.5 on 2023-10-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_is_first_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_first_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_pending_approval',
            field=models.BooleanField(default=True),
        ),
    ]
