# Generated by Django 4.2.5 on 2023-10-20 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applicant_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=10)),
                ('current_occupation', models.CharField(max_length=100)),
                ('current_salary', models.IntegerField()),
                ('qualifications_experience', models.CharField(max_length=200)),
                ('desired_salary', models.IntegerField()),
                ('desired_position_company', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=150)),
                ('post_transition_salary', models.IntegerField(blank=True, null=True)),
                ('post_transition_company', models.CharField(blank=True, max_length=100, null=True)),
                ('interview_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('選考中', '選考中'), ('面接中', '面接中'), ('内定', '内定')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_file', models.ManyToManyField(blank=True, to='applicant.applicantfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
    ]
